services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: klinik_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - klinik_network

  webserver:
    image: nginx:alpine
    container_name: klinik_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - klinik_network

  db:
    image: mysql:5.7
    container_name: klinik_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: klinik_aesthetic
      MYSQL_ROOT_PASSWORD: klinik123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - klinik_network

networks:
  klinik_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
